language: php
php:
  - '7.0'
before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y nodejs
  - npm install -g yarn
  - yarn
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - bash ./syllabus.sh
  - cat syllabus.md
