language: php
php:
  - '7.0'
cache:
  directories:
  - node_modules
  - $HOME/.npm
  - $HOME/.composer/cache/files
before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y nodejs
  - npm install -g yarn
  - yarn
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
script:
  - yarn run gulp production
  - cat syllabus.md
